3557 message size upper bounds
marc-casperlabs/casper-node pull request #8
Opened 2023-01-25 14:15 UTC by Boiethios

2023-01-25 16:23 UTC, marc-casperlabs approved these changes
Looks really good so far!

2023-01-25 16:23 UTC, marc-casperlabs commented on node/src/components/consensus/highway_core/highway/vertex.rs
> +                endorsers: vec![
There's always only one endorser here in a valid message?

2023-01-25 16:23 UTC, marc-casperlabs commented on node/src/components/consensus/protocols/highway.rs
> +pub fn min_rounds_per_era(
Maybe add an additional doc comment on what this function does, just to be sure.

2023-02-01 16:25 UTC, marc-casperlabs requested changes
Some changes still, but we're close :)

2023-02-01 16:25 UTC, marc-casperlabs commented on node/src/components/consensus/highway_core/evidence.rs
> +                                .unwrap(),
Let's put an `expect` with a helpful message here.

2023-02-01 16:25 UTC, marc-casperlabs commented on node/src/components/consensus/highway_core/evidence.rs
> +                                    .unwrap()
See above.

2023-02-01 16:25 UTC, marc-casperlabs commented on node/src/components/consensus/highway_core/evidence.rs
> +                                    .unwrap()
See above.

2023-02-01 16:25 UTC, marc-casperlabs commented on node/src/components/consensus/highway_core/evidence.rs
> +                        .unwrap()
Same. We never use `.unwrap`, `.expect` is the bare minimum.

2023-02-01 16:25 UTC, marc-casperlabs commented on node/src/components/consensus/highway_core/state/index_panorama.rs
> +            IndexObservation::NextSeq(LargestSpecimen::largest_specimen(estimator))
If we're giving a specific variant, can we put a comment here on why we're sure it's the largest? It's trivial in this case, but it can't hurt.

2023-02-01 16:25 UTC, marc-casperlabs commented on node/src/components/consensus/protocols/highway.rs
> +/// - The minimum era height, which is the maximum number of blocks that can be created in one era.
That would be the _minimum_ number of blocks required in one era, right?

2023-02-01 16:25 UTC, marc-casperlabs commented on node/src/components/consensus/protocols/highway.rs
> +    // This can be derived entirely from the chainspec core_config.
We can remove this comment, I think.

2023-02-01 16:25 UTC, marc-casperlabs commented on node/src/components/consensus/protocols/highway.rs
> +        let min_rounds_per_era = max_rounds_per_era(
The variable should probably be renamed?

2023-02-01 16:25 UTC, marc-casperlabs commented on node/src/components/consensus/protocols/highway.rs
> +pub fn max_rounds_per_era(
Can you add a simple unit test for this function, with reasonable values and confirm with @fizyk20 that it is correct?

2023-02-01 16:25 UTC, marc-casperlabs commented on node/src/components/network/message.rs
> +                "recent_era_count" => unimplemented!("chainspec: unbonding_delay - auction_delay"),
Please look up the current values for all of these from the production chainspec and fill them in.

2023-02-01 16:25 UTC, marc-casperlabs commented on node/src/testing/specimen.rs
> +            .unwrap();
```.expect("did not expect `validator_count` failing to convert to `usize`")```

2023-02-01 16:25 UTC, marc-casperlabs commented on node/src/testing/specimen.rs
> +            .unwrap(),
No unwraps please, just expects. I won't point out the rest :)

2023-02-01 16:25 UTC, marc-casperlabs commented on node/src/testing/specimen.rs
> +fn largest_chain_name<E: SizeEstimator>(estimator: &E) -> String {
Can we put descriptive comments on all functions in this file that don't have docs yet?

2023-02-01 16:25 UTC, marc-casperlabs commented on node/src/types/block/approvals_hashes.rs
> +                map.insert("key1", Digest::hash(""));
These keys need to be from constants, specifically `APPROVALS_CHECKSUM_NAME` and `EXECUTION_RESULTS_CHECKSUM_NAME`. These are longer than the examples.

2023-02-01 16:25 UTC, marc-casperlabs commented on node/src/types/block/approvals_hashes.rs
> +                map.insert("key1", Digest::hash(""));
Also consider using `LargestSpecimen::largest_specimen()` for the hash.

2023-02-01 17:44 UTC, Boiethios commented on node/src/components/consensus/highway_core/evidence.rs
> +                                .unwrap(),
I thought they were OK in tests since there already is a bunch of them

2023-02-02 16:52 UTC, marc-casperlabs commented on node/src/testing/specimen.rs
> +//impl LargestSpecimen for Digest {
This can't stay though :)

2023-02-02 17:25 UTC, Boiethios commented on node/src/testing/specimen.rs
> +//impl LargestSpecimen for Digest {
Sorry…

2023-02-02 18:06 UTC, marc-casperlabs approved these changes

2023-02-02 18:07 UTC, merged